blog/urls.py
from blog.apps import BlogConfig
from django.urls import path

from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleDeleteView, ArticleUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete')
]

catalog/urls.py
from catalog.apps import CatalogConfig
from django.urls import path

from catalog.views import ProductListView, FeedbackCreateView, ProductDetailView, ProductDeleteView, \
    ProductCreateView, ProductUpdateView, VersionCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('contacts/', FeedbackCreateView.as_view(), name='contacts'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_item'),
    path('products/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/edit/<int:pk>', ProductUpdateView.as_view(), name='product_edit'),
    path('version/create/<int:pk>', VersionCreateView.as_view(), name='version_create')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='заголовок')
    slug = models.CharField(**NULLABLE, max_length=500, verbose_name='слаг')
    text = models.TextField(verbose_name='текст')
    preview = models.ImageField(**NULLABLE, verbose_name='превью')
    create_date = models.DateTimeField(auto_now=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='флаг публикации')
    views_count = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.title}\n{self.text}"

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    preview = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='превью')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='цена за покупку')
    create_data = models.DateTimeField(auto_now=True, verbose_name='дата создания')
    update_data = models.DateTimeField(auto_now_add=True, **NULLABLE, verbose_name='дата последнего изменения')

    user = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE)

    is_published = models.BooleanField(default=True, verbose_name='опубликовано')

    def __str__(self):
        return f"{self.name} - {self.category} - {self.price}"

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        permissions = [
            (
                'set_is_published',
                'Can publish post'
            ),
            (
                'set_description',
                'Can change description'
            ),
            (
                'set_category',
                'Can change category'
            )
        ]


class Feedback(models.Model):
    name = models.CharField(max_length=100, verbose_name='имя')
    phone = models.CharField(max_length=12, verbose_name='телефон')
    message = models.TextField(verbose_name='сообщение')

    def __str__(self):
        return f"{self.message}"

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    num_version = models.IntegerField(verbose_name='номер версии')
    name = models.CharField(**NULLABLE, max_length=150, verbose_name='название')
    is_current = models.BooleanField(verbose_name='текущая версия')

    def __str__(self):
        return f"{self.num_version} -> {self.name}"

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version

BAN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'preview', 'category', 'price', 'is_published')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if any(word in cleaned_data.lower() for word in BAN_WORDS):
            raise forms.ValidationError('Запрещённый контент')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        if any(word in cleaned_data.lower() for word in BAN_WORDS):
            raise forms.ValidationError('Запрещённый контент')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = "__all__"

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if any(word in cleaned_data.lower() for word in BAN_WORDS):
            raise forms.ValidationError('Запрещённый контент')

        return cleaned_data

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Article
from pytils.translit import slugify


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'text', 'preview', 'is_published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'text', 'preview', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class ArticleListView(ListView):
    model = Article

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:list')

catalog/views.py
from django.urls import reverse_lazy, reverse
from django.forms import inlineformset_factory

from catalog.forms import ProductForm, VersionForm
from catalog.utils import load_contacts_to_json
from catalog.models import Product, Feedback, Version
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.shortcuts import redirect
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        for product in context['object_list']:
            active_version = product.version_set.filter(is_current=True).first()
            if active_version:
                product.active_version_number = active_version.num_version
                product.active_version_name = active_version.name
            else:
                product.active_version_number = None
                product.active_version_name = None

        return context


class FeedbackCreateView(LoginRequiredMixin, CreateView):
    model = Feedback
    fields = ['name', 'phone', 'message']
    success_url = reverse_lazy('catalog:list')

    def form_valid(self, form):
        if form.is_valid():
            feedback = form.save
            load_contacts_to_json(feedback.name, feedback.phone, feedback.message)

        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductDeleteView(DeleteView, LoginRequiredMixin):
    model = Product
    success_url = reverse_lazy("catalog:list")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            self.object.user = self.request.user
            self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = ['catalog.set_is_published', 'catalog.set_description', 'catalog.set_category']

    def get_success_url(self):
        return reverse('catalog:product_edit', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        product_pk = self.kwargs['pk']
        product = Product.objects.get(pk=product_pk)
        if formset.is_valid():
            formset.instance = self.object
            Version.objects.filter(product=product).exclude(pk=product_pk).update(is_current=False)
            formset.save()

        return super().form_valid(form)


class VersionCreateView(LoginRequiredMixin, CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:list')

    def form_valid(self, form):
        product_pk = self.kwargs['pk']
        product = Product.objects.get(pk=product_pk)
        form.instance.product = product
        Version.objects.filter(product=product).exclude(pk=product_pk).update(is_current=False)
        return super().form_valid(form)

catalog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-start">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Новая статья</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <h1>Хотите удалить статью?</h1>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" type="button" class="btn btn-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h1>{{object.title}} ({{object.slug}})</h1>
                <p>{{object.text}}</p>
                <p>{{object.create_date}}</p>
                <p>{{object.views_count}}</p>
            </div>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-start">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Новая статья</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{form.as_p}}
                    </div>
                    <input class="btn btn-primary w-100" type="submit" value="Send"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/blog/article_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <a href="{% url 'blog:create' %}" type="button" class="btn btn-lg btn-block btn-outline-primary">
        Создать
    </a>
</div>
<div class="row text-center">
    {% for object in object_list %}
    <div class="col-3 mb-3 mt-3">
        <div class="card mb-3 h-100 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.title}}</h4>
                <img class="col-10 row-10" src="{% mediapath_tag object.preview %}">
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{object.slug}}</h1>
                <p>{{object.text|truncatechars:20}}</p>
                <p>{{object.views_count}}</p>
                <a href="{% url 'blog:view' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">читать</a>
                <a href="{% url 'blog:edit' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">редактировать</a>
                <a href="{% url 'blog:delete' object.pk%}" type="button" class="btn btn-lg btn-block btn-danger">удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}