blog/urls.py
from blog.apps import BlogConfig
from django.urls import path

from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleDeleteView, ArticleUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', ArticleListView.as_view(), name='list'),
    path('view/<int:pk>', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete')
]

catalog/urls.py
from catalog.apps import CatalogConfig
from django.urls import path

from catalog.views import ProductListView, FeedbackCreateView, ProductDetailView, ProductDeleteView, \
    ProductCreateView, ProductUpdateView, VersionCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('contacts/', FeedbackCreateView.as_view(), name='contacts'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_item'),
    path('products/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/edit/<int:pk>', ProductUpdateView.as_view(), name='product_edit'),
    path('version/create/<int:pk>', VersionCreateView.as_view(), name='version_create')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    preview = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='превью')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='цена за покупку')
    create_data = models.DateTimeField(auto_now=True, verbose_name='дата создания')
    update_data = models.DateTimeField(auto_now_add=True, **NULLABLE, verbose_name='дата последнего изменения')

    user = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE)

    is_published = models.BooleanField(default=True, verbose_name='опубликовано')

    def __str__(self):
        return f"{self.name} - {self.category} - {self.price}"

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        permissions = [
            (
                'set_is_published',
                'Can publish post'
            ),
            (
                'set_description',
                'Can change description'
            ),
            (
                'set_category',
                'Can change category'
            )
        ]


class Feedback(models.Model):
    name = models.CharField(max_length=100, verbose_name='имя')
    phone = models.CharField(max_length=12, verbose_name='телефон')
    message = models.TextField(verbose_name='сообщение')

    def __str__(self):
        return f"{self.message}"

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    num_version = models.IntegerField(verbose_name='номер версии')
    name = models.CharField(**NULLABLE, max_length=150, verbose_name='название')
    is_current = models.BooleanField(verbose_name='текущая версия')

    def __str__(self):
        return f"{self.num_version} -> {self.name}"

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version

BAN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'preview', 'category', 'price', 'is_published')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if any(word in cleaned_data.lower() for word in BAN_WORDS):
            raise forms.ValidationError('Запрещённый контент')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        if any(word in cleaned_data.lower() for word in BAN_WORDS):
            raise forms.ValidationError('Запрещённый контент')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = "__all__"

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if any(word in cleaned_data.lower() for word in BAN_WORDS):
            raise forms.ValidationError('Запрещённый контент')

        return cleaned_data

catalog/views.py
from django.urls import reverse_lazy, reverse
from django.forms import inlineformset_factory

from catalog.forms import ProductForm, VersionForm
from catalog.utils import load_contacts_to_json
from catalog.models import Product, Feedback, Version
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.shortcuts import redirect
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        for product in context['object_list']:
            active_version = product.version_set.filter(is_current=True).first()
            if active_version:
                product.active_version_number = active_version.num_version
                product.active_version_name = active_version.name
            else:
                product.active_version_number = None
                product.active_version_name = None

        return context


class FeedbackCreateView(LoginRequiredMixin, CreateView):
    model = Feedback
    fields = ['name', 'phone', 'message']
    success_url = reverse_lazy('catalog:list')

    def form_valid(self, form):
        if form.is_valid():
            feedback = form.save
            load_contacts_to_json(feedback.name, feedback.phone, feedback.message)

        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductDeleteView(DeleteView, LoginRequiredMixin):
    model = Product
    success_url = reverse_lazy("catalog:list")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            self.object.user = self.request.user
            self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = ['catalog.set_is_published', 'catalog.set_description', 'catalog.set_category']

    def get_success_url(self):
        return reverse('catalog:product_edit', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        product_pk = self.kwargs['pk']
        product = Product.objects.get(pk=product_pk)
        if formset.is_valid():
            formset.instance = self.object
            Version.objects.filter(product=product).exclude(pk=product_pk).update(is_current=False)
            formset.save()

        return super().form_valid(form)


class VersionCreateView(LoginRequiredMixin, CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:list')

    def form_valid(self, form):
        product_pk = self.kwargs['pk']
        product = Product.objects.get(pk=product_pk)
        form.instance.product = product
        Version.objects.filter(product=product).exclude(pk=product_pk).update(is_current=False)
        return super().form_valid(form)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
        {% block content %}
        {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static '/js/bootstrap.bundle.min.js'%}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Контактный телефон" required></textarea>
                    </div>
                    <input class="btn btn-primary w-100" type="submit" value="Send"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/feedback_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Контактный телефон" required></textarea>
                    </div>
                    <input class="btn btn-primary w-100" type="submit" value="Send"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-center">
    {% for object in object_list %}
    <div class="col-3 mb-3 mt-3">
        <div class="card mb-3 h-100 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$ {{object.price}}</h1>
                <p>{{object.description|truncatechars:100}}</p>
                <a href="{% url 'catalog:product_item' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/item.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <div class="card">
        <div class="card-body">
            <img class="col-5 row-5" src="{% mediapath_tag object.preview %}">
            <h1>{{object.name}}</h1>
            <p>{{object.description}}</p>
            <p>{{object.category}}</p>
            <p>{{object.price}}$</p>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-start">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление продукта</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <h1>Хотите удалить продукт?</h1>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'catalog:list' %}" type="button" class="btn btn-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <div class="card">
        <div class="card-body">
            <img class="col-5 row-5" src="{% mediapath_tag object.preview %}">
            <h1>{{object.name}}</h1>
            <p>{{object.description}}</p>
            <p>{{object.category}}</p>
            <p>{{object.price}}$</p>
        </div>
    </div>
</div>
{%endblock%}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form method="post" action="" class="form-floating" enctype="multipart/form-data">
    <div class="row center">
        {% csrf_token %}
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {% if object %}
                        Изменить продукт
                        {% else %}
                        Новый продукт
                        {% endif %}
                    </h4>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        {{form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-primary w-100" type="submit" value="Send">Сохранить
                    </button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Версии
                </div>
                <div class="card-body">
                    {{ formset.management_from }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-center">
    <a href="{% url 'catalog:product_create' %}" type="button" class="btn btn-lg btn-block btn-outline-primary">
        Создать
    </a>
</div>
<div class="row text-center">
    {% for object in object_list %}
    <div class="col-3 mb-3 mt-3">
        <div class="card mb-3 h-100 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
                {% if object.active_version_number %}
                    <p>Текущая версия {{object.active_version_number}}</p>
                    <p>{{object.active_version_name}}</p>
                {% endif %}
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$ {{object.price}}</h1>
                <p>{{object.description|truncatechars:100}}</p>
                <a href="{% url 'catalog:product_item' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</a>
                <p>Автор - {{object.user.email|default:"Без автора"}}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:version_create' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Добавить версию</a>
                <a href="{% url 'catalog:product_edit' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-warning">Изменить</a>
                <a href="{% url 'catalog:product_delete' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form method="post" action="" class="form-floating" enctype="multipart/form-data">
    <div class="row center">
        {% csrf_token %}
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {% if object %}
                        Изменить версию
                        {% else %}
                        Новая версия
                        {% endif %}
                    </h4>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        {{form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-primary w-100" type="submit" value="Send">Сохранить
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}